### PR TITLE
#142 - Added `mfa_code` option to `login()`.

### PR DESCRIPTION
**Pull request by unacceptable**

### CODE REVIEW

**Comment by unacceptable** [comment]
There were a couple of minor errors with the documentation, but they have been fixed and this should be ready for PR now.

**Comment by jmfernandes** [comment]
Hey man good stuff. I don't have my computer on me and I'm out of town, instead of doing the pip install line in the authentication.py line, could you add that package as a requirement. In the setup.py file. There should already be a requirement for the 'requests' package. Just add it to the list and add the commit to this pull request.

**Comment by unacceptable** [comment]
Ah, good deal!  I Will do that and test now.

**Comment by unacceptable** [comment]
This should be ready for review again whenever you get a chance.

**Pull request merged**
