### PR TITLE
Market sell order shouldn't set price during normal hours

### PR DESCRIPTION
**Pull request by anson-vandoren**
If a price is set for a market sell order when the instrument is somewhat volatile, there is a high chance the order will not be filled. Sending price for a market sell order is only required during extended hours, but not during normal hours.

This change removes `price` from the payload if `extendedHours` is False, otherwise sends the price as before

### CODE REVIEW

**Comment by anson-vandoren** [comment]
Updated since it seems that only market sell orders don't require the price parameter set, but market buy orders still require it. Not sure why this is the case.

**Comment by anson-vandoren** [comment]
Looks like this is not accomplishing what I want, which was basically to get an "actual" market order which executes immediately.

It looks like Robinhood app/website sets a +/- 5% price limit when sending market orders. I'll close this PR and submit a separate one to get this behavior instead

**Comment by jmfernandes** [comment]
@anson-vandoren also could you do me a favor and NOT change any formatting. I know the code isnt currently compliant with PEP8 but it makes it difficult for me to read through the changes if the formatting is different as well.

**Comment by anson-vandoren** [comment]
@jmfernandes ah, crap. I had turned off my formatter on the other ones, but re-cloned this time and forgot to disable it again.

**Pull request closed without merging**
